### ISSUE TITLE
heirline failed

### ISSUE THREAD

**Issue by Talleyrand-34** [kabinspace/AstroNvim_user#3]
Error detected while processing User Autocommands for "AstroColorScheme":
Error executing lua callback: ...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:398: attempt to index field 'statusline' (a nil value)
stack traceback:
        ...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:398: in function 'on_colorscheme'
        /home/asada-san/.config/nvim/lua/configs/heirline.lua:292: in function </home/asada-san/.config/nvim/lua/configs/heirline.lua:292>
        [C]: in function 'nvim_exec_autocmds'
        /home/asada-san/.config/nvim/lua/core/utils/init.lua:162: in function </home/asada-san/.config/nvim/lua/core/utils/init.lua:162>

When i run astronvim in a fresh install, it appears this message, i dont know how to solved it.

Sorry if here it is not the place to ask but i would like to know any piece of info i can gather

**Comment by kabinspace** [comment]
Please check [this](https://github.com/AstroNvim/AstroNvim/issues/1523)
