### ISSUE TITLE
Can't install the profile 😭 

### ISSUE THREAD

**Issue by askrix** [kabinspace/AstroNvim_user#5]
Good evening @kabinspace :wave:,

A couple of days ago, I discovered AstroVim for me and have been trying to install the beautiful profile you built and have been maintaining. 

More precise, I have been following the installation instructions from `README.md` and the error message I am currently seeing is 
<img width="513" alt="Screenshot 2023-04-17 at 21 18 32" src="https://user-images.githubusercontent.com/37047795/232588891-99238ca6-3f49-47f2-bccd-8ebc60c3fb7c.png">

It is coming from running the command `nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'`. 🤔 The command is not terminating.

The outputs of `nvim --version` on my MacBook Pro (2019's version) running Ventura 13.2.1 macOS:
```sh
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.9.0/share/nvim"

Run :checkhealth for more info
```

Many thanks in advance for your help!

Cheers, 🍻

**Comment by Balssh** [comment]
I also have some problems with the config, namely I get errors on the init neoscroll and wakatime plugins.

**Comment by PsyMaza** [comment]
similar problem

**Comment by 0nyr** [comment]
Same...
```
Error detected while processing command line:
E492: Not an editor command: PackerSync
```

**Comment by azinsharaf** [comment]
Astronvim is no longer using packersync anymore at least in v3 nightly channel.

**Comment by 0nyr** [comment]
I have been trying for hours to modify the code by using [the packer bootstrap code snippet](https://github.com/wbthomason/packer.nvim#bootstrapping), but no matter what I have tried, I will always fall on the following error: 

```
(base) [onyr@kenzael nvim]$ nvim  --headless -c 'quitall'
packer.nvim is loaded
./?.lua;/usr/share/luajit-2.1.0-beta3/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua
Error detected while processing /home/onyr/.config/nvim/init.lua:
Failed to load astronvim.bootstrap
/home/onyr/.config/nvim/lua/astronvim/bootstrap.lua:89: attempt to index local 'settings' (a boolean value)
Failed to load astronvim.lazy

/home/onyr/.config/nvim/lua/astronvim/bootstrap.lua:89: attempt to index local 'settings' (a boolean value)
Failed to load astronvim.mappings

/home/onyr/.config/nvim/lua/astronvim/bootstrap.lua:89: attempt to index local 'settings' (a boolean value)
```

From what I have been able to understand, astrovim is looking for a table of user configs inside `user.init` (see the [docs](https://astronvim.com/Configuration/config_options), but also support fallback config files as in the project... Anyway, I must go to sleep. I'm probably going to try to make a new custom project from scratch... Maybe the following can help.

**Comment by 0nyr** [comment]
> Astronvim is no longer using packersync anymore at least in v3 nightly channel.

Ok, then, what should be done to adapt current codebase to the new AstroVim ? What is the new packet manager ?

**Comment by azinsharaf** [comment]
Packer.nvim has been replaced by lazy.nvim in astronvim.

**Comment by azinsharaf** [comment]
I am not the maintainer but I see it has a v3 branch. That could work with current astronvim.

**Comment by kabinspace** [comment]
Hi @askrix ,

I would like to express my sincere apologies for not addressing your issue sooner. I recently discovered that an issue had been opened, and I was less active during the past few months, which contributed to the delay in noticing and resolving it.

Since the issue was opened, there have been updates to the configuration, including a switch to a different plugin manager. I also went ahead and removed the outdated command in the readme.

Given that this issue is now resolved with the updates, I'll go ahead and close it. Feel free to reopen it if you encounter any new issues.

**Comment by 0nyr** [comment]
Thanks, that's good work. Anyway no worries, I managed to fix the issue myself. Take care.
